### ISSUE TITLE
Android端末で通知機能が使えない

### ISSUE THREAD

**Issue by Erga-mion** [Erga-mion/heatstroke_report_app#5]
通知呼び出しをするタイミングで、デバッグが落ちる

**Comment by Erga-mion** [comment]
エミュレータ(Nexus One API 29)で、`getApi`の`getLocation`が終了しない。

**Comment by Erga-mion** [comment]
```dart  
Future<void> getLocation() async {
    Position currentLocation;
    try {
      currentLocation = await getCurrentPosition(desiredAccuracy: LocationAccuracy.medium);
    }
    catch(e){
      currentLocation = null;      
    }
    userLocation = currentLocation;
  }

**Comment by Erga-mion** [comment]
ここで止まっているようだ。
```dart
currentLocation = await getCurrentPosition(desiredAccuracy: LocationAccuracy.medium);

**Comment by Erga-mion** [comment]
エミュレータ側の位置設定をすることで解決できた。
https://github.com/Baseflow/flutter-geolocator/issues/434#issuecomment-631508832

**Comment by Erga-mion** [comment]
通知を出す処理の呼び出しで、アプリが落ちる。以下に、アプリが落ちる後に発生したログを載せる。
``` 
D/AndroidRuntime( 9684): Shutting down VM
E/AndroidRuntime( 9684): FATAL EXCEPTION: main
E/AndroidRuntime( 9684): Process: com.example.heatstroke_report_app, PID: 9684
E/AndroidRuntime( 9684): java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AndroidRuntime( 9684): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3797)
E/AndroidRuntime( 9684): 	at android.app.ActivityThread.access$1400(ActivityThread.java:219)
E/AndroidRuntime( 9684): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1870)
E/AndroidRuntime( 9684): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 9684): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 9684): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 9684): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9684): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 9684): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime( 9684): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AndroidRuntime( 9684): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon(FlutterLocalNotificationsPlugin.java:188)
E/AndroidRuntime( 9684): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:146)
E/AndroidRuntime( 9684): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:688)
E/AndroidRuntime( 9684): 	at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(ScheduledNotificationReceiver.java:45)
E/AndroidRuntime( 9684): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3788)
E/AndroidRuntime( 9684): 	... 8 more
I/Process ( 9684): Sending signal. PID: 9684 SIG: 9
Lost connection to device.
Exited (sigterm)
